---

- name: Install gnupg
  ansible.builtin.package:
    name: gnupg
    state: "{{ potos_remmina_gnupg_enforce_latest | ternary('latest', 'present') }}"

- name: Install software-properties-common
  ansible.builtin.package:
    name: software-properties-common
    state: "{{ potos_remmina_softpropcomm_enforce_latest | ternary('latest', 'present') }}"

- name: Add apt repository for remmina
  ansible.builtin.shell: |
    apt-add-repository ppa:remmina-ppa-team/remmina-next -y
  args:
    creates: /etc/apt/sources.list.d/remmina-ppa-team-ubuntu-remmina-next-*.list

- name: Install remmina
  ansible.builtin.package:
    name: remmina
    state: "{{ potos_remmina_enforce_latest | ternary('latest', 'present') }}"

- name: Install remmina rdp plugin
  ansible.builtin.package:
    name: remmina-plugin-rdp
    state: "{{ potos_remmina_rdpplugin_enforce_latest | ternary('latest', 'present') }}"

- name: Install remmina secret plugin
  ansible.builtin.package:
    name: remmina-plugin-secret
    state: "{{ potos_remmina_secretplugin_enforce_latest | ternary('latest', 'present') }}"

- name: Register all available users
  ansible.builtin.find:
    paths: /home/
    recurse: no
    file_type: directory
  register: potos_remmina_found_users
  when:
    - potos_remmina_install_connections is true

- name: ensure .local/share/remmina exists
  ansible.builtin.file:
    path: '/home/{{ item.pw_name }}/.local/share/remmina'
    owner: '{{ item.pw_name }}'
    group: '{{ item.pw_name }}'
    mode: '0644'
    state: directory
  loop: '{{ potos_remmina_found_users.files }}'

- name: Install remmina connections
  ansible.builtin.copy:
    src: 'remmina/connections/'
    dest: '/home/{{ item.pw_name }}/.local/share/remmina'
    owner: '{{ item.pw_name }}'
    group: '{{ item.pw_name }}'
    mode: '0644'
  loop: '{{ potos_remmina_found_users.files }}'
  when:
    - potos_remmina_install_connections is true
    - potos_remmina_found_connections is defined
    - potos_remmina_found_connections is iterable
    - potos_remmina_found_connections is not string
    - (potos_remmina_found_connections | length > 0)
    - potos_remmina_found_users is defined
    - potos_remmina_found_users is iterable
    - potos_remmina_found_users is not string
    - (potos_remmina_found_users | length > 0)
