---

- name: Install gnupg
  ansible.builtin.package:
    name: gnupg
    state: "{{ potos_remmina_gnupg_enforce_latest | ternary('latest', 'present') }}"
  changed_when: false  # Debug purposes


- name: Add apt repository for remmina
  ansible.builtin.shell: |
    apt-add-repository ppa:remmina-ppa-team/remmina-next -y
    apt update

      #- name: Add apt repository for remmina
      #ansible.builtin.apt_repository:
        #repo: ppa:remmina-ppa-team/remmina-next
        #validate_certs: false
        #state: present

- name: Install remmina
  ansible.builtin.package:
    name: remmina
    state: "{{ potos_remmina_enforce_latest | ternary('latest', 'present') }}"

- name: Install remmina rdp plugin
  ansible.builtin.package:
    name: remmina-plugin-rdp
    state: "{{ potos_remmina_rdpplugin_enforce_latest | ternary('latest', 'present') }}"

- name: Install remmina secret plugin
  ansible.builtin.package:
    name: remmina-plugin-secret
    state: "{{ potos_remmina_secretplugin_enforce_latest | ternary('latest', 'present') }}"
