---

- name: Install gnupg
  ansible.builtin.package:
    name: gnupg
    state: "{{ potos_remmina_gnupg_enforce_latest | ternary('latest', 'present') }}"

- name: Add apt repository for remmina
  ansible.builtin.command: apt-add-repository ppa:remmina-ppa-team/remmina-next -y
  args:
    creates: /etc/apt/sources.list.d/remmina-ppa-team-ubuntu-remmina-next-jammy.list

- name: Install remmina
  ansible.builtin.package:
    name: remmina
    state: "{{ potos_remmina_enforce_latest | ternary('latest', 'present') }}"

- name: Install remmina rdp plugin
  ansible.builtin.package:
    name: remmina-plugin-rdp
    state: "{{ potos_remmina_rdpplugin_enforce_latest | ternary('latest', 'present') }}"

- name: Install remmina secret plugin
  ansible.builtin.package:
    name: remmina-plugin-secret
    state: "{{ potos_remmina_secretplugin_enforce_latest | ternary('latest', 'present') }}"
