---

- name: Add apt repository for remmina
  ansible.builtin.apt_repository:
    repo: ppa:remmina-ppa-team/remmina-next

- name: Install remmina
  ansible.builtin.package:
    name: remmina
    state: "{{ potos_remmina_enforce_latest | ternary('latest', 'present') }}"

- name: Install remmina rdp plugin
  ansible.builtin.package:
    name: remmina-plugin-rdp
    state: "{{ potos_remmina_rdp-plugin_enforce_latest | ternary('latest', 'present') }}"

- name: Install remmina secret plugin
  ansible.builtin.package:
    name: remmina-plugin-secret
    state: "{{ potos_remmina_secret-plugin_enforce_latest | ternary('latest', 'present') }}"
